# Generated by Django 2.2.6 on 2021-08-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('source_code', models.URLField(blank=True)),
                ('tools', models.CharField(max_length=250)),
            ],
        ),
    ]
