# Generated by Django 2.2.6 on 2021-08-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0002_auto_20210801_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField(default='Kolawole is a programmer')),
                ('para2', models.TextField(blank=True)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
