# Generated by Django 2.2.6 on 2021-08-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0003_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='para1',
            new_name='para',
        ),
    ]
